name: "StableDiffusionXL High-Resolution Image Generation (1K -> 4K)"
version: "sdxl1.0"

diffusion:
  # pretrained_model_name_or_path: "stabilityai/stable-diffusion-xl-base-1.0"
  pretrained_model_name_or_path: "cache/models--stabilityai--stable-diffusion-xl-base-1.0/snapshots/462165984030d82259a11f4367a4eed129e94a7b"
  guidance_scale: 7.5
  diffusion_steps: 50
  # target_height: [2048, 3072, 4096]
  # target_width: [2048, 3072, 4096]
  target_height: 4096
  target_width: 4096

  noising_steps: 15
  freeu: False

dwt:
  steps: 5
  level: 1
  wave: "db4"
  mode: "symmetric"